(define (problem week1)
    (:domain Guidance)
    (:objects shop1 shop2 shop3 - shop
        list1 list2 list3 list4 list5 - list)   
    (:init (= (people-at-shop shop1) 0)
        (= (people-at-shop shop2) 0)
        (= (people-at-shop shop3) 0)
        (shop-option list1 shop1)
        (shop-option list2 shop2)
        (shop-option list2 shop1)
        (shop-option list3 shop1)
        (shop-option list4 shop1)
        (shop-option list5 shop2)        
    )
    (:goal 
        (and (forall (?l - list)
                (list-set ?l)
            )
            (forall (?s - shop)
                (< (people-at-shop ?s) 4) 
            )
                       
        )
    )
)

