(define (problem week2)
(:domain Guidance)
(:objects shop0 shop1 shop2 - shop
list0 list1 list2 list3 list4 - list)
(:init (= (people-at-shop shop0) 0)
(= (people-at-shop shop1) 10)
(= (people-at-shop shop2) 0)
(shop-option list0 shop1)
(shop-option list0 shop2)
(shop-option list1 shop1)
(shop-option list1 shop2)
(shop-option list2 shop1)
(shop-option list2 shop2)
(shop-option list3 shop1)
(shop-option list3 shop2)
(shop-option list4 shop1)
(shop-option list4 shop2)
)
(:goal            
        (and (forall (?l - list)
            (list-set ?l)
        )(and (<= (people-at-shop shop0) 9))
(and (<= (people-at-shop shop1) 10))
(and (<= (people-at-shop shop2) 11))

                    
        )
        )
        )
        